site_name: pacman-mirrors
repo_url: https://gitlab.manjaro.org/applications/pacman-mirrors
docs_dir: data/docs
theme:
  name: readthedocs
nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
